version: '3.9'

services:
  api:
    build: .
    ports:
      - '5000:5000'
    container_name: bookmystay-api
    environment:
      - DATABASE_URL=postgres://prisma:prisma@db:5432/db_name
    depends_on:
      - db
    networks:
      - my_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:13
    restart: always
    container_name: bookmystay-api-db
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=db_name
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db-data:

networks:
  my_network:
    driver: bridge
