version: "3.9"
services:
  # api-service:
  #   stdin_open: true
  #   build:
  #     context: .
  #   container_name: api-service
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - EXTERNAL_PORT=5000
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres-db-soko:5432/esoko_DB?schema=public&connection_timeout=300
  #     - POSTGRES_HOST=postgres-db-soko
  #   restart: always
  #   networks:
  #     - gateway
  #   volumes:
  #     - .:/home/node/api
  #     - node_modules:/home/node/api/node_modules
  postgres-db-soko:
    image: postgres:14.1-alpine
    container_name: postgres-db-soko
    hostname: postgres-db-soko
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres-db-soko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esoko_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - gateway

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
    networks:
      - gateway

volumes:
  postgres-data:
    driver: local
  redisDB:
  node_modules:


networks:
  gateway:
    driver: bridge
