version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://prisma:prisma@db:5432/db_name
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=db_name
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
